api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        # https://api-platform.com/docs/core/jwt/#configuring-api-platform
        api_keys:
            apiKey:
                name: Authorization
                type: header
    show_webby: false
    title: 'PayTop Technical Test API'
