version: '3'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-paytop}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-paytop}
            POSTGRES_USER: ${POSTGRES_USER:-paytop}
        volumes:
            - db-data:/var/lib/postgresql/data:rw

    rabbitmq:
        image: rabbitmq:3.7-management-alpine
        ports: [ "5672" ]

volumes:
    db-data:
